language: php

notifications:
  email:
    on_success: never
    on_failure: change

jobs:
  fast_finish: true
  allow_failures:
    - env: WP_VERSION=nightly
  include:
    - name: PHPUnit (PHP 7.4, WordPress latest)
      php: 7.4
      env: WP_VERSION=*
    - name: PHPUnit (PHP 7.4, WordPress latest Multisite)
      php: 7.4
      env: WP_VERSION=* WP_MULTISITE=1
    - name: PHPUnit (PHP 7.4, WordPress nightly)
      php: 7.4
      env: WP_VERSION=nightly
    - name: PHPUnit (PHP 5.6, WordPress 4.9)
      php: 5.6
      env: WP_VERSION=4.9.15

before_install: composer validate --strict

install:
  - composer update phpunit/phpunit --with-dependencies
  - |
    [ "$WP_VERSION" != "nightly" ] && composer require "roots/wordpress:$WP_VERSION" "wp-phpunit/wp-phpunit:$WP_VERSION" --update-with-dependencies || true
  - |
    [ "$WP_VERSION" = "nightly" ]  && bin/install-wp-tests.sh tests root '' localhost $WP_VERSION || true

script: composer test

services:
  - mysql
