language: php

services:
  - mysql

php:
  - 7.4
  - 5.6

env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  include:
    - php: 7.4
      env: WP_VERSION=latest WP_MULTISITE=1

install:
  - composer update phpunit/phpunit --no-install
  - composer install

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: composer test
