language: php

services:
  - mysql

php:
  - 7.3
  - 7.2
  - 7.1
  - 5.6

env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  include:
    - php: 7.3
      env: WP_VERSION=latest WP_MULTISITE=1

install: composer install

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: composer test
