language: php

php:
  - 5.3
  - 7.0
  - 7.1
  - hhvm

env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  include:
    - php: 7.0
      env: WP_VERSION=latest WP_MULTISITE=1

install: composer install

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: composer test
